lyz-code/autoimport

.github/workflows/tests.yml
Correct the tests make command
=> ci: correct make command to run the tests

docs/index.md
=> Fix link to contributing documentation

CHANGELOG.md, requirements-dev.txt
=> chore: update dependencies

docs/editor_integration.md
Remove manual steps required to run autoimport with ale before it was merged
=> docs: ale now supports autoimport by default

src/autoimport/__init__.py, tests/e2e/test_cli.py
=> tests: add typing to click runner

.cruft.json, docs/requirements.txt, mkdocs.yml, requirements-dev.in, requirements-dev.txt, src/autoimport/services.py, tests/unit/test_services.py
Correctly manage multiline imports and strings
=> Correctly manage multiline imports and strings

.cruft.json, Makefile, pyproject.toml, src/autoimport/__init__.py
=> chore: update python project template

docs/requirements.txt, requirements-dev.txt
=> chore: update requirements

.cruft.json, .github/workflows/update.yml, Makefile, docs/contributing.md, docs/index.md, docs/requirements.in, docs/requirements.txt, mypy.ini, pyproject.toml, requirements-dev.txt, requirements.txt, setup.py, src/autoimport/entrypoints/cli.py, src/autoimport/model.py, tests/conftest.py, tests/unit/test_services.py
If an import statement was indented, when moving to the top, the
indentation wasn't removed
perf: common import statements are now run sooner
They are run before the search in the developing project package, which
is a slower operation.
chore: update the template
chore: update requirements
ci: hourly update the requirements
=> fix: wrong import indentation when moving up the imports.

.github/workflows/tests.yml
=> ci: run pull requests with forks as origin

.pre-commit-config.yaml, Makefile, docs/requirements.txt, requirements-dev.txt, src/autoimport/model.py, tests/unit/test_services.py
Closes #70
feat: add BaseModel and Faker to common statements
=> fix: respect shebang and leading comments

src/autoimport/model.py, tests/unit/test_services.py
Closes #70 
fix: respect document trailing newline
=> fix: respect newlines in the header section

docs/editor_integration.md
=> style: rephrase editor integration header

docs/index.md
=> docs: feature smart-imports as an alternative

.pre-commit-config.yaml
=> ci: change black pre-commit version to master

src/autoimport/model.py
=> perf: add new Enum import alias

.cruft.json, .github/workflows/update.yml, Makefile, docs/requirements.txt, pyproject.toml, requirements-dev.in, requirements-dev.txt, requirements.txt
ci: configure pytest to run tests in parallel
ci: update pip on the make update step
=> ci: remove the git hooks on the update workflow

src/autoimport/model.py, tests/unit/test_services.py
=> fix: prevent autoimport from importing same package many times

src/autoimport/model.py
=> fix: avoid RecursionError when searching for packages inside the project

src/autoimport/model.py, tests/unit/test_services.py
=> fix: let autoimport handle empty files

mypy.ini, src/autoimport/model.py, tests/unit/test_services.py
feat: support comments in simple import statementsgn
=> feat: added datetime and ModelFactory to the default imports

src/autoimport/model.py, tests/unit/test_services.py
=> fix: support the removal of from x import y as z statements

.github/dependabot.yml
=> ci: disable dependabot until it supports pdm

pyproject.toml
=> fix: correct the package building

.github/workflows/tests.yml, .github/workflows/update.yml
=> ci: correct the update workflow to use mypy well

.github/workflows/build.yml, .github/workflows/install.yml, .github/workflows/tests.yml, .github/workflows/update.yml
=> ci: add workflow_dispatch events

.cruft.json, .github/workflows/build.yml, .github/workflows/tests.yml, .github/workflows/update.yml, .gitignore, .pre-commit-config.yaml, Makefile, README.md, docs/index.md, docs/reference.md, mkdocs.yml, pdm.lock, pyproject.toml, src/autoimport/entrypoints/cli.py, src/autoimport/model.py, src/autoimport/services.py, src/autoimport/version.py, tests/conftest.py, tests/e2e/test_cli.py, tests/unit/test_entrypoints.py, tests/unit/test_extract_package.py, tests/unit/test_version.py
=> chore: update cruft template

.cruft.json, .github/workflows/build.yml, .github/workflows/tests.yml, .github/workflows/update.yml, .gitignore, .pre-commit-config.yaml, Makefile, README.md, docs/index.md, docs/reference.md, mkdocs.yml, pdm.lock, pyproject.toml, src/autoimport/entrypoints/cli.py, src/autoimport/model.py, src/autoimport/services.py, src/autoimport/version.py, tests/conftest.py, tests/e2e/test_cli.py, tests/unit/test_entrypoints.py, tests/unit/test_extract_package.py, tests/unit/test_version.py
=> Update cruft template

.cruft.json, .github/workflows/tests.yml, .github/workflows/update.yml, Makefile, mkdocs.yml, pyproject.toml
=> chore: update cruft

.cruft.json, Makefile, pdm.lock, pyproject.toml
=> chore: update template

pyproject.toml, src/autoimport/__main__.py
=> feat: added __main__.py file (fixes #210)

pdm.lock, pyproject.toml, src/autoimport/model.py, tests/unit/test_services.py
Closes #225
More info at https://github.com/lyz-code/autoimport/issues/225
=> fix: allow imports with dots

docs/index.md, pdm.lock, src/autoimport/model.py, tests/conftest.py, tests/e2e/test_cli.py
It's unmaintained and has a vulnerability so we need to change from
tmpdir to tmp_path
=> fix: remove dependency with py

pdm.lock, pyproject.toml, src/autoimport/entrypoints/cli.py, src/autoimport/model.py
=> chore: update deps

.gitignore, pdm.lock, src/autoimport/entrypoints/cli.py, tests/unit/test_entrypoints.py
=> ci: fix update pipeline

.github/ISSUE_TEMPLATE/bug.md
Simple way to report its version
=> bug.md: mention "autoimport --version"

.github/workflows/install.yml, .github/workflows/tests.yml, mkdocs.yml, pdm.lock, pyproject.toml
fix: drop support for Python 3.7
fix: switch from pdm-pep517 to pdm-backend
chore: updte requirements
=> feat: support Python 3.11
